### ISSUE TITLE
Stereo Audio Issue

### ISSUE THREAD

**Issue by TechnoMysterio** [BobMowzie/MowziesMobs#108]
This is an issue relating to the sound effects Mowzie's Mobs has. It's fairly minor, but it's a simple enough fix and can help tidy up the mod a bit.

Some of the sounds in this mod are in stereo, which can be a problem in Minecraft. I've done sound design for Minecraft mods before, and it took me a while to discover this myself, but stereo sounds in Minecraft are played in both ears, no matter what. So, say, if a mob with sounds like this is standing next to you, it'll sound like it's right in front of you anyway, due to how Minecraft processes stereo sounds.

With this in mind, I'd recommend going over the sounds for the mod and converting ones which should be directional, such as sounds for mobs or other ones that come from a position in the world, to mono. This would make sure that players know what direction something is without looking and it would help to cut down on the mod's filesize. Stereo sounds, however, are fine for things like music or big events, such as vanilla's Wither spawning sound.

I also wanted to ask a quick question about the sounds the mod has, just about where you get them from? I'm always interested in finding out where people get their sound effects from, as it helps me with my own stuff.

By the way, if you see issues like this cropping up on other mod's Github issue pages, that'll probably be me. I may or may not be going on a small internet crusade to resolve this very specific and entirely trivial issue that only some mods have.

**Comment by BobMowzie** [comment]
I was not aware! I will work on this. Thanks!

Many of the sounds in MM, particularly the voices, are recordings of my friends. Sound effects are edited from Youtube or The Sounds Resource found here: https://www.sounds-resource.com/

**Comment by UberApril** [comment]
I'de like to add on to this to say that having sound physics with this mod crashes anytime the Naga produced a sound (it diving or screeching whatever it is). it could be due to the stereo sounds but i'm not too sure, this is an old report but i just experienced crashing paired with sound physics and i was scrolling through issues to see if anybody else came across it. 

Crash report: 
[crash-2020-01-25_21.10.34-server.txt](https://github.com/BobMowzie/MowziesMobs/files/4112806/crash-2020-01-25_21.10.34-server.txt)
