### ISSUE TITLE
Barakoa summons should only follow while you have the mask on

### ISSUE THREAD

**Issue by MarioSMB** [BobMowzie/MowziesMobs#183]
It would be nice if the Barakoa tribesmen you summon would only follow you when you have the summoning mask on.  
This way you would be forced to use a specific helmet to have a tribe protecting you, and it would allow leaving the tribe at home when you want to go on a peaceful journey.

**Comment by BobMowzie** [comment]
I took a slightly different approach. You can now right-click your followers to return them to their masks. Their health gets converted to durability and back when you spawn them again.
I've also made player-controlled Barakoa significantly stronger so that the Sol Visage is much more useful.
You are still able to wear whatever helmet you want once the Barakoa have been spawned. This is intentional.
