### ISSUE TITLE
Crash with Arcane Archives after updating to Mowzie's Mobs - 1.5.5

### ISSUE THREAD

**Issue by SirAron111** [BobMowzie/MowziesMobs#224]
Crash with Arcane Archives after updating to Mowzie's Mobs - 1.5.5. i have no idea what caused it but here is the log 
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/4731790/latest.log)
the problem should be near the very end as far as i understand logs, something about ticking entety barako king. "Vanilla fix" claims its this mod conflicting with the Arcane one but thats all i got sry.

**Comment by BobMowzie** [comment]
Seems like Arcane Archives isn't handling a null case when adjusting looting enchantment levels after players kill a mob. This might be causing problems with Mowzie's Mobs because some of my mobs drop their loot after their death animation is finished and they have been removed from the world.

"java.lang.NullPointerException: null
	at com.aranaira.arcanearchives.events.EventHandler.onLooting(EventHandler.java:597)"

I suggest reporting this issue on the Arcane Archives Github.

**Comment by noobanidus** [comment]
The `damageSource` value for the LootingLevelEvent should never be null, so there never should be a null case for us to handle. However, it looks like you've fixed it in 689e99e83430792.

**Comment by noobanidus** [comment]
No worries! It means I don't have to do the struggle of two releases with different Mixin versions so people can actually use the mod properly, so I'm happy!
