### ISSUE TITLE
Singleplayer world with latest version of Meowzie's Mobs loaded causes instant crash-to-desktop.

### ISSUE THREAD

**Issue by DoYouLikeToEatBee** [BobMowzie/MowziesMobs#225]
[relevant crash log text.txt](https://github.com/BobMowzie/MowziesMobs/files/4733439/relevant.crash.log.text.txt)

Game crashes when specific singleplayer world is loaded up.
World worked fine on the immediate past version before updating to latest.
1.12.2

**Comment by BobMowzie** [comment]
What is Whitedraco / switchbow? Some other mod is causing a compatibility issue here.

**Comment by DoYouLikeToEatBee** [comment]
that is the Switchbow mod by WhiteDraco.

**Comment by BobMowzie** [comment]
Seems that the Switchbow mod doesn't handle a null case when it adjusts looting modifiers after killing a mob. I'm guessing that this is causing problems with my mobs because some of them drop their loot after they finish playing their death animations and are removed from the world.
"java.lang.NullPointerException: Ticking entity
[Info: 2020-06-05 01:34:15.7102735: GameCallbacks.cpp(158)] Game/game () Info at de.Whitedraco.switchbow.event.EventHandler.LootingLevelEvent(EventHandler.java:130)"

I recommend posting this to the Switchbow Github instead.

**Comment by DoYouLikeToEatBee** [comment]
I managed to fix the crash by removing MowziesMobs from my game temporarily, running the world without it, closing the game, then running the world again with the mod reinstalled.

**Comment by BobMowzie** [comment]
Yes, that will remove all instances of my mobs from the world.
