### ISSUE TITLE
1.7.10 generating terrain crash

### ISSUE THREAD

**Issue by LavaDragonz** [BobMowzie/MowziesMobs#319]
I am using the mod in my modpack and was able to isolate the problem by using this mod only and it's LLibrary dependency, it happens whether i have AnimationAPI or not and seems to be triggered when generating a world or entering new terrain. The full crash report: https://controlc.com/27d87e9f

**Comment by BobMowzie** [comment]
This is a crash caused by the generation of the Wroughtnaut’s structure. I am not sure why this is happening for you and not other users, so the best advice I have for you is to disable Ferrous Wroughtnaut generation in the mod config.

Feel free to use some other mod to allow them to spawn via other means without their structures.

**Comment by LavaDragonz** [comment]
Yep, seems to have worked when i set Wroughtnaut's value to 0 in the configs. No more crashes for a while now, and uh i hope submitting the report has helped in some way and i also found someone with a similar issue with mowzie's mobs submitted to github before i decided to contact you: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/442. Thank you very much and keep on the amazing work!
