### ISSUE TITLE
Wroughtnaut chamber chunk bounds error

### ISSUE THREAD

**Issue by cursinorock** [BobMowzie/MowziesMobs#375]
Forge 6.1.3
The game crash or froze when im in the nether, with out the mod, work just fine :T
Single player.

[crash-2021-03-31_02.26.07-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6233983/crash-2021-03-31_02.26.07-server.txt)

**Comment by Muuge** [comment]
It's because ferrous dreadnaught lairs are still spawning outside the overworld. Just experienced a similar crash although it wasnt until after the lair rendered.

**Comment by cursinorock** [comment]
get it but only happens in the nether :T

**Comment by nick-dukellis-pcc** [comment]
I think I'm having the same issue. Mowzie's Mobs was recently added to Valhelsia 3, and I'm crashing in the end due to some hitch related to generating the Wroughtnaut chambers. Two crash reports, though the crash is consistent with 8 logged so far. Crashes upon the "Generating world" message, directly after "Joining World".  Attempting now to relocate my character with NBTExplorer, and going to avoid the end. This is anecdotal, but since it seems like it /can/ happen in any dimension but /is/ happening in the end and nether, maybe it happens when the structure attempts to generate in midair, with no surrounding terrain to latch onto? 

https://pastebin.com/FHGerSVB

https://pastebin.com/QCB1i8Dg

**Comment by Muuge** [comment]
Yeah, to add to what was posted it does seem the wroughtnaut chambers are spawning in dimensions other than just the end. Tried to temp remedy the issue by adding !Nether,!End to the list of blacklisted biomes but it might be ignoring the biome configs since one spawned in the end, but it could be BetterEnd mod not properly tagging their biomes. Gonna confirm via getting a list of biome tags via the TellMe mod.

**Comment by BobMowzie** [comment]
No no the chambers are ignoring their dimension config due to my mistake. That has already been fixed. This is a separate issue and I know what I need to do to fix it. Rarely a Wroughtnaut chamber will scan into adjacent unloaded chunks while looking for cave walls. That causes this crash. Thanks for your help, though.
