### ISSUE TITLE
The Ferrous Wroughtnaut is too easy

### ISSUE THREAD

**Issue by OfficialLambdax** [BobMowzie/MowziesMobs#555]
In the description it says: "Only the bravest of adventurers would dare to challenge a Ferrous Wroughtnaut."
That sounds challenging. But a simple wooden sword while having zero armor is enough to kill him.

https://www.youtube.com/watch?v=7W1-zuQrSro

I think he should be much more challenging.

mowziesmobs-1.5.19.jar at 1.16.5

**Comment by BobMowzie** [comment]
I don’t believe a mob is difficult because it requires certain gear to beat. In fact, I’ve had just as many complaints that the Ferrous Wroughtnaut is too hard. He’s designed to be an early/mid game boss that teaches players a new way of thinking about Minecraft combat. Once players learn to watch his animations and identify his weakness, he is not supposed to be hard. The rewards you receive from defeating him are proportionally useful to this difficulty.

If you would like the fight to be harder, you can change that in the config.

**Comment by BobMowzie** [comment]
The mob’s description is for flavor and lore, and should not be taken as literal game design metrics.
