### ISSUE TITLE
Mowziesmob structure gen causes lag spikes

### ISSUE THREAD

**Issue by Krampus69** [BobMowzie/MowziesMobs#562]
Hello hello :wave:
I'm in charge of doing stress tests on an unreleased modpack and I've come across lag spikes due to mowziesmob structure gen : 

I used spark to find the culprit, here is the viewer for more infos :
https://spark.lucko.me/cuZyKVViWs

Any suggestions on how to handle these without removing this awesome mod ?

(You're doing an amazing btw gg for all the excellent content 🙏 )

Have a great day :)

**Comment by Krampus69** [comment]
Some infos about the version : 

Minecraft 1.16.5
mowziesmobs-1.5.19
Forge 36.2.9

the latest.log
[latest.log](https://github.com/BobMowzie/MowziesMobs/files/7741390/latest.log)

the debug.log
[debug.log](https://github.com/BobMowzie/MowziesMobs/files/7741391/debug.log)

**Comment by BobMowzie** [comment]
The issue is caused by Lithium's "getChunk" function, which replaces the vanilla version of this function. I use this to check and avoid nearby structures when mob spawning.

You have two options:

1. Remove Lithium.
2. Clear all "avoid structures" entries from the Mowzie's Mobs spawn configs.

Either way, I suggest you report this to Lithium.
