### ISSUE TITLE
Crash with Geckolib Iris Compat Mod (NeoForge 1.20.1)

### ISSUE THREAD

**Issue by cncz42** [BobMowzie/MowziesMobs#761]
This mod crashes with [Iris/Oculus & GeckoLib Compat](https://modrinth.com/mod/geckoanimfix), attached is a log of an instance running just embeddium, oculus, Geckolib Iris Compat Mod, geckolib, and this mod.

[latest.log](https://github.com/nvb-uy/GeckoAnimFix/files/15449962/latest.log)
[crash-2024-05-26_18.53.27-client.txt](https://github.com/BobMowzie/MowziesMobs/files/15449985/crash-2024-05-26_18.53.27-client.txt)

**Comment by doppeltrouble** [comment]
i have the same problem and it also causes mana and artifice to crash upon loading the modpack saying it was caused by 
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mowziesmobs.mixins.json:GeoModelMixin] from phase [DEFAULT] in config [mowziesmobs.mixins.json] FAILED during APPLY 
but doesnt generate a config file
not sure if the problem is at mnas end or at yours

**Comment by doppeltrouble** [comment]
i can also open a seperate issue if this is required

**Comment by BobMowzie** [comment]
Please try this version instead:
https://legacy.curseforge.com/minecraft/mc-mods/mowzies-mobs/files/5380391

**Comment by doppeltrouble** [comment]
thanks it loads and works really well its just that the naga fang dagger is quote too blunt to use according to either better combat or natural progression not sure which maybe fix that if that isnt to much work but again insane mods thanks for maintaining and making it

**Comment by doppeltrouble** [comment]
sorry not either of these mods not really sure whats causing it

**Comment by doppeltrouble** [comment]
also theres a config option for me to fix it its actually all good
