### ISSUE TITLE
Barakoa's mask doesn't give effect if wore by a mob

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#85]
The villager is equipped with a mask, but he doesn't have the responding buff.
https://cdn.discordapp.com/attachments/394202999209328650/516535620684742656/2018-11-26_14.38.18.png

**Comment by mser7** [comment]
don't mind those effects, those are from the Everlastingabilities mod

**Comment by BobMowzie** [comment]
I cannot view that image.
This is intentional. With the exception of the Barakoana, I need the Barakoa to be functionally identical. I don’t want players to be confused about their differing abilities, and certain buffs like Swiftness might upset the carefully designed behaviors I have created.
I justify this with the fact that the Barakoa are not wearing their masks, they ARE their masks. Different properties may emerge when a players wears one of them.

**Comment by BobMowzie** [comment]
Oh, wait, you’re referring to other mobs. I suppose I could include them in the mask effects. Not that it would be noticeable.

**Comment by mser7** [comment]
Could you make the particle effect from the mask visible around the mob?

**Comment by BobMowzie** [comment]
Wouldn’t that be distracting?

**Comment by mser7** [comment]
The mask on the mob itself is more distracting IMO
